name: Build and Test (Cross-Platform)

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Build and Test on macOS
        if: runner.os == 'macOS'
        run: |
          clang -std=c11 -Iincludes -Isrc src/*.c tests/armel_test.c -o build/armel_tests
          ./build/armel_tests

      - name: Build and Test on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          gcc -std=c11 -Iincludes -Isrc src/*.c tests/armel_test.c -o build/armel_tests
          ./build/armel_tests

      - name: Setup MinGW and build on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install mingw -y
          export PATH="/c/ProgramData/chocolatey/bin:/c/tools/mingw64/bin:$PATH"
          gcc -std=c11 -Iincludes -Isrc src/*.c tests/armel_test.c -o build/armel_tests.exe
          ./build/armel_tests.exe